config/routes.rb
Rails.application.routes.draw do

devise_for :customer, controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}

  namespace :public do
   root to: 'homes#top'
   resources :items, only: [:index, :show]
   resources :cart_items do
     collection do
       delete 'destroy_all'
      end
     end
   get 'orders/verification' => 'orders#verification',as: 'verification'
   get 'orders/thanks' => 'orders#thanks', as: 'thanks'
   resources :orders, only: [:new, :create ,:index, :show]
   resources :addresses
   resources :customers, only: [:show,:edit]
   patch "customers/:id/edit" => 'customers#update'
   patch "cart_items/:id/edit" => 'cart_items#update'
   get 'customers/:id/verfication' => 'customers#verfication', as: 'verfication'
   patch 'customers/:id/withdrawal' => 'customers#withdrawal', as:'withdrawal'
  end


  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
   root to: 'homes#top'
   resources :items
   resources :genres
   resources :customers
   resources :orders
   resources :order_details
   patch "genres/:id/edit" => 'genres#update'
   patch "items/:id/edit" => 'items#update'
   patch "customers/:id/edit" => 'customers#update'
  end


  get "about" => 'public/homes#about'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer


  def subtotal
    item.with_tax_price * amount
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def active_for_authentication?
    super && (is_deleted == false)
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre , optional: true
  has_many :cart_items
  has_many :order_details
  attachment :image

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

    private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

 def index
  @genre = Genre.new
  @genres = Genre.all
 end

 def create
  @genre = Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
 end

 def edit
  @genre = Genre.find(params[:id])
 end

 def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path
 end

 def genre_params
   params.require(:genre).permit(:name)
 end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

 def index
  @genres = Genre.all
  @items = Item.all
 end

 def new
   @item = Item.new
   @genres = Genre.all
 end

 def create
   @genres = Genre.all
   @item = Item.new(item_params)
   @item.save
   redirect_to admin_item_path(@item)
 end

 def show
  @cart_item = CartItem.new
  @item = Item.find(params[:id])
 end

 def edit
  @genres = Genre.all
  @item = Item.find(params[:id])
 end

 def update
  @item = Item.find(params[:id])
  @item.update!(item_params)
  redirect_to admin_item_path(@item)
 end

 def item_params
   params.require(:item).permit(:name,:image,:introduction,:price, :genre)
 end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def after_sign_in_path_for(resource)
  case resource
  when Admin
    admin_root_path
  when Customer
    public_customer_path(resource)
  end
end

def after_sign_up_path_for(resource)
  case resource
  when Admin
    admin_path
  when Customer
    public_customer_path(resource)
  end
end

 def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        public_root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email])
      devise_parameter_sanitizer.permit(:sign_in,keys:[:email])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3"></div>
   <div class="col-md-5 mt-5">
    <h2><sapn class="bg-secondary">ジャンル編集</sapn></h2><br><br>
    <%= form_with model:@genre, url:edit_admin_genre_path, local:true do |f| %>
     ジャンル名　　　　
    <%= f.text_field :name %>
   </div>
   <div class="col-md-3 mt-5">
   <br><br><br><br>
     <%= f.submit '変更を保存',class:"btn btn-success" %>
    <% end %>
   </div>
  </div>
 </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3"></div>
  <div class="col-mr-9 mt-5">
   <h2><span class="bg-secondary">ジャンル一覧・追加</span></h2><br>
    <%= form_with model:@genre, url:admin_genres_path, local:true do |f| %>
     ジャンル名
     <%= f.text_field :name %>
     <%= f.submit '新規登録',class:"btn btn-success" %>
    <% end %>
    <br><br>
    
      <table class="table">
       <thead class="thead-light">
        <tr>
         <th scope="col">ジャンル</th><th></th>
        </tr>
       </thead>
       <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td>
           <%= genre.name %>
          </td>
          <td>
           <%= link_to "編集",edit_admin_genre_path(genre.id) ,class:"btn btn-success" %><br><br>
          </td>
        </tr>
        </tbody>
     <% end %>
    </table>
   </div>
 </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3"></div>
  <div class="col-mr-9 mt-5">
   <h2><span class="bg-secondary">商品編集</span></h2><br>
 <%= form_with model:@item, url:edit_admin_item_path, local:true do |f| %>
  商品画像　　
   <%= f.attachment_field :image %><br><br>
  商品名　　　
   <%= f.text_field :name %><br><br>
  商品説明　　
   <%= f.text_area :introduction %><br><br>
  ジャンル　　
    <%= collection_select(:genre, :name, @genres, :id, :name) %><br><br>
  税抜価格　　
   <%= f.text_field :price %>円<br><br>
   <%= f.submit '変更を保存', class:"btn btn-success" %>

<% end %>
  </div>
  </div>
 </div>

app/views/admin/items/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-8"></div>
   <div class="col-md-3">
    <button type="button" class=" rounded-circle p-0" style="width:2rem;height:2rem;"><%= link_to '＋' ,new_admin_item_path %></button>
   </div>
  </div>
 <div class="row">
  <div claaa="col-md-3"></div>
   <div class="col-md-9 mt-5">
    <h2><span class="bg-secondary">商品一覧画面</span></h2>
    <table class="table mt-5">
     <thead class="thead-light">
      <tr>
       <th scope="col">商品ID</th>
       <th scope="col">商品名</th>
       <th scope="col">税込価格</th>
      </tr>
     </thead>
     <tbody>
      <% @items.each do |item| %>
      <tr>
       <th scope="col"><%= item.id %></th>
       <th scope="col">
        <%= link_to admin_item_path(item) do %>
         <%= item.name %></th>
        <% end %>
       <th scope="col"><%= item.price %></th>
      </tr>
      <% end %>
     </tbody>
    </table>
   </div>
  </div>
 </div>

app/views/admin/items/new.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3 mt-5"><h2><span class="bg-secondary">商品新規登録</span></h2></div>
  <div class="col-md-9 mt-5">
 <%= form_with model:@item, url:admin_items_path, local:true do |f| %><br><br>
  商品画像　　
   <%= f.attachment_field :image %><br><br>
  商品名　 　　
   <%= f.text_field :name %><br><br>
  商品説明　　
   <%= f.text_field :introduction %><br><br>
  税抜価格　　
   <%= f.text_field :price %>円<br><br>
  <%= f.submit'新規登録', class:"btn btn-success" %>
 <% end %>
 </div>
 </div>
 </div>
 

app/views/admin/items/show.html.erb
<div class="container">
 <div class="row mt-5">
  <div class="col-md-5">
   <h2><span class="bg-secondary">商品詳細</span></h2>
   <br>
   <%= attachment_image_tag @item, :image, size: '400x330' %>
  </div>
    <div class0="col-md-7 mt-5"><br>
    商品名
    <%= @item.name %><br><br>
    商品説明
    <%= @item.introduction %><br><br>

   税込価格（税抜き価格）
    <%= @item.price %>円<br><br>

<%= link_to "編集する", edit_admin_item_path(@item), class:"btn btn-success" %>

  </div>
 </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
 <div class="row mt-5">
  <div class="col-md-12">
   <h2>注文履歴詳細</h2>
    <table>
      <tr>
        <th width="100" height="50">購入者</th>
        <td><%= @order.name %></td>
      </tr>
      <tr>
        <th width="100" height="50">注文日</th>
        <td><%= @order.created_at %></td>
      </tr>
      <tr>
        <th width="100" height="50">配送先</th>
        <td>
          <br>
          〒<%= @order.postal_code %>
          <%= @order.address %>
          <p><%= @order.name %></p>
        </td>
      </tr>
      <tr>
        <th width="100" height="50">支払方法</th>
        <td><%= @order.payment_method_i18n %></td>
      </tr>
     </table>
     </div>
     </div>
     <div class="row mt-3" >
     <div class="col-md-8">
     <table class="table">
       <thead class="thead-light">
        <tr>
         <th scope="col">商品名</th>
         <th scope="col">単価（税込）</th>
         <th scope="col">数量</th>
         <th scope="col">小計</th>
        </tr>
       </thead>
       <tbody>
        <tr>
          <td>
            <% @order.order_details.each do |order_detail| %>
           <p>
             <%= order_detail.item.name %>
           </p>
          <% end %>

          </td>
          <td>
           <% @order.order_details.each do |order_detail| %>
           <p>
             <%= order_detail.item.price %>
           </p>
          <% end %>
          </td>
          <td>
           <% @order.order_details.each do |order_detail| %>
           <p>
             <%= order_detail.amount %>
           </p>
          <% end %>
          </td>
          <td>
            <% @order.order_details.each do |order_detail| %>
           <p>
             <%= order_detail.amount*order_detail.item.price %>
           </p>
          <% end %>
          </td>
        </tr>
        </tbody>
      </table>
     </div>
     <div class="col-md-4">
      <p><h4>商品合計</h4>
      <%= @order.total_payment %>円
      </p>
      <p><h4>送料</h4>
      800円
      </p>
      <p><h4>請求金額合計</h4>
      <%= @order.total_payment += 800 %>円
      </p>
     </div>

  </div>
</div>