config/routes.rb
Rails.application.routes.draw do

devise_for :customer, controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}

  namespace :public do
   root to: 'homes#top'
   resources :items, only: [:index, :show]
   resources :cart_items do
     collection do
       delete 'destroy_all'
      end
     end
   get 'orders/verification' => 'orders#verification',as: 'verification'
   get 'orders/thanks' => 'orders#thanks', as: 'thanks'
   resources :orders, only: [:new, :create ,:index, :show]
   resources :addresses
   resources :customers, only: [:show,:edit]
   patch "customers/:id/edit" => 'customers#update'
   patch "cart_items/:id/edit" => 'cart_items#update'
   get 'customers/:id/verfication' => 'customers#verfication', as: 'verfication'
   patch 'customers/:id/withdrawal' => 'customers#withdrawal', as:'withdrawal'
  end


  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
   root to: 'homes#top'
   resources :items
   resources :genres
   resources :customers
   resources :orders
   resources :order_details
   patch "genres/:id/edit" => 'genres#update'
   patch "items/:id/edit" => 'items#update'
   patch "customers/:id/edit" => 'customers#update'
  end


  get "about" => 'public/homes#about'
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def active_for_authentication?
    super && (is_deleted == false)
  end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

    private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController

 before_action :reject_customer, only: [:create]


  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_registration_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

def after_sign_out_path_for(resource)
    public_root_path # ログアウト後に遷移するpathを設定
  end


  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
 <div class="row mt-5">
  <div class="col-md-3"></div>
  <div class="col-md-9">
   <h2><span class="bg-secondary"><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</span></h2>
  </div>
 </div>
 <div class="row mt-5">
  <div class="col-md-3"></div>
  <div class="col-md-9">
     <table class="mt-5">
      <tbody>
       <tr>
        <td>
         会員ID
        </td>
        <td></td> <td></td>
        <td>
         <%= @customer.id %>
        </td>
       </tr>
       <%= form_with model:@customer,url:edit_admin_customer_path, local:true do |f| %>
       <tr>
        <td>
         氏名
        </td>
         <td></td> <td></td>
        <td>
         <%= f.text_field :first_name %>
         
 <%= f.text_field :last_name %>
        </td>
       </tr>
       <tr>
        <td>
         フリガナ
        </td>
         <td></td> <td></td>
        <td>
          <%= f.text_field :first_name_kana %>
 <%= f.text_field :last_name_kana %>
        </td>
       </tr>
       <tr>
        <td>
        郵便番号
        </td>
         <td></td> <td></td>
        <td>
         <%= f.text_field :postal_code %>

        </td>
       </tr>
       <tr>
        <td>
         住所
        </td>
         <td></td> <td></td>
        <td>
         <%= f.text_field :address %>
        </td>
       </tr>
       <tr>
        <td>
         電話番号
        </td>
         <td></td> <td></td>
        <td>
          <%= f.text_field :telephone_number %>
        </td>
       </tr>
       <tr>
        <td>
         メールアドレス
         </td>
           <td></td> <td></td>
        <td>
         <%= f.text_field :email %>
        </td>
       </tr>
       <tr>
        <td>
         会員ステータス
        </td>
         <td></td> <td></td>
           <td>
          <%= f.text_field :is_deleted %>
          </td>
         </tr>
        </tbody>
       </table><br><br>
      <%= f.submit "変更を保存", class:"btn btn-success" %>
      <% end %>
      </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row mt-5">
   <div class="col-2"></div>
     <div class="col-10">
      <table class="table">
       <thead class="thead-light">
         <tr>
           <th scope="col">会員ID</th>
           <th scope="col">氏名</th>
           <th scope="col">メールアドレス</th>
           <th scope="col">ステータス</th>
         </tr>
       </thead>
       <% @customers. each do |customer| %>
       <tbody>
         <tr>
           <th scope="row"><%= customer.id %></th>
           <td><%= link_to admin_customer_path(customer) do %>
                <%= customer.first_name %>
                <%= customer.last_name %>
               <% end %>
           </td>
           <td><%= customer.email %></td>
           <td><%= customer.is_deleted ? '退会':'有効' %></td>
           <% end %>
         </tr>
       </tbody>
      </table>
     </div>
    </div>
  </div>

app/views/admin/customers/show.html.erb
<div class="container">
 <div class="row mt-5">
  <div class="col-md-3"></div>
  <div class="col-md-9">
   <h2><span class="bg-secondary"><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</span></h2>
  </div>
 </div>
 <div class="row mt-5">
  <div class="col-md-3"></div>
  <div class="col-md-9">
     <table class="mt-5">
      <tbody>
       <tr>
        <td>
         会員ID
        </td>
        <td></td> <td></td>
        <td>
         <%= @customer.id %>
        </td>
        
       </tr>
       <tr>
        <td>
         氏名
        </td>
         <td></td> <td></td>
        <td>
         <%= @customer.first_name %>
      <%= @customer.last_name %>
        </td>
       </tr>
       <tr>
        <td>
         フリガナ
        </td>
         <td></td> <td></td>
        <td>
         <%= @customer.first_name_kana %>
      <%= @customer.last_name_kana %>
        </td>
       </tr>
       <tr>
        <td>
        郵便番号
        </td>
         <td></td> <td></td>
        <td>
         <%= @customer.postal_code %>
        </td>
       </tr>
       <tr>
        <td>
         住所
        </td>
         <td></td> <td></td>
        <td>
         <%= @customer.address %>
        </td>
       </tr>
       <tr>
        <td>
         電話番号
        </td>
         <td></td> <td></td>
        <td>
         <%= @customer.telephone_number %>
        </td>
       </tr>
       <tr>
        <td>
         メールアドレス
         </td>
           <td></td> <td></td>
        <td>
         <%= @customer.email %>
        </td>
       </tr>
       <tr>
        <td>
         会員ステータス
        </td>
         <td></td> <td></td>
           <td>
          <%= @customer.is_deleted ? '退会':'有効'  %>
          </td>
         </tr>
        </tbody>
       </table><br><br>
      <%= link_to "編集する",edit_admin_customer_path(@customer), class:"btn btn-success" %>
     
      <%= link_to "注文履歴一覧を見る", admin_order_details_path, class:"btn btn-primary" %>
     </div>
  </div>
</div>