config/routes.rb
Rails.application.routes.draw do

devise_for :customer, controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}

  namespace :public do
   root to: 'homes#top'
   resources :items, only: [:index, :show]
   resources :cart_items do
     collection do
       delete 'destroy_all'
      end
     end
   get 'orders/verification' => 'orders#verification',as: 'verification'
   get 'orders/thanks' => 'orders#thanks', as: 'thanks'
   resources :orders, only: [:new, :create ,:index, :show]
   resources :addresses
   resources :customers, only: [:show,:edit]
   patch "customers/:id/edit" => 'customers#update'
   patch "cart_items/:id/edit" => 'cart_items#update'
   get 'customers/:id/verfication' => 'customers#verfication', as: 'verfication'
   patch 'customers/:id/withdrawal' => 'customers#withdrawal', as:'withdrawal'
  end


  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
   root to: 'homes#top'
   resources :items
   resources :genres
   resources :customers
   resources :orders
   resources :order_details
   patch "genres/:id/edit" => 'genres#update'
   patch "items/:id/edit" => 'items#update'
   patch "customers/:id/edit" => 'customers#update'
  end


  get "about" => 'public/homes#about'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer


  def subtotal
    item.with_tax_price * amount
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def active_for_authentication?
    super && (is_deleted == false)
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre , optional: true
  has_many :cart_items
  has_many :order_details
  attachment :image

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

 def index
  @genre = Genre.new
  @genres = Genre.all
 end

 def create
  @genre = Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
 end

 def edit
  @genre = Genre.find(params[:id])
 end

 def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path
 end

 def genre_params
   params.require(:genre).permit(:name)
 end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

 def index
  @genres = Genre.all
  @items = Item.all
 end

 def new
   @item = Item.new
   @genres = Genre.all
 end

 def create
   @genres = Genre.all
   @item = Item.new(item_params)
   @item.save
   redirect_to admin_item_path(@item)
 end

 def show
  @cart_item = CartItem.new
  @item = Item.find(params[:id])
 end

 def edit
  @genres = Genre.all
  @item = Item.find(params[:id])
 end

 def update
  @item = Item.find(params[:id])
  @item.update!(item_params)
  redirect_to admin_item_path(@item)
 end

 def item_params
   params.require(:item).permit(:name,:image,:introduction,:price, :genre)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def after_sign_in_path_for(resource)
  case resource
  when Admin
    admin_root_path
  when Customer
    public_customer_path(resource)
  end
end

def after_sign_up_path_for(resource)
  case resource
  when Admin
    admin_path
  when Customer
    public_customer_path(resource)
  end
end

 def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        public_root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email])
      devise_parameter_sanitizer.permit(:sign_in,keys:[:email])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/customerskk/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customerskk/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if admin_signed_in? %>
     <div class="container">
       <div class="row mt-5 pb-5 border-bottom border-dark">
         <div class="col-md-4">
          <div class="logo">
           <h1>
             <p>
              &nbsp;&nbsp;NaganoCake
             </p>
           </h1>
          </div>
         </div>
         <div class="col-md-1"></div>
         <div class="col-md-7">
          <%= link_to "商品一覧", admin_items_path,class: "btn btn-outline-dark" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to "会員一覧", admin_customers_path,class: "btn btn-outline-dark" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to "注文履歴一覧", admin_root_path,class: "btn btn-outline-dark" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to "ジャンル一覧", admin_genres_path,class: "btn btn-outline-dark" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class: "btn btn-outline-dark" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         </div>
       </div>
     </div>
     <% elsif customer_signed_in? %>
     <div class="container">
       <div class="row mt-5 pb-5 border-bottom border-dark">
         <div class="col-md-4">
          <div class="logo">
           <h1>
             <p>
              &nbsp;&nbsp;NaganoCake
             </p>
           </h1>
          </div>
         </div>
         <div class="col-md-3">
           <% if customer_signed_in? %>
           <%= current_customer.first_name %>
           <%= current_customer.last_name %>様がログイン中
          <% end %>
         </div>
         <div class="col-md-5">
     <%= link_to "マイページ", public_customer_path(current_customer.id),class: "btn btn-outline-dark" %>
     <%= link_to "商品一覧",public_items_path,class: "btn btn-outline-dark" %>
     <%= link_to "カート", public_cart_items_path,class: "btn btn-outline-dark" %>
     <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class: "btn btn-outline-dark" %>
     </div>
       </div>
     </div>
     <% else %>
     <div class="container">
       <div class="row mt-5 pb-5 border-bottom border-dark">
         <div class="col-md-4">
          <div class="logo">
           <h1>
             <p>
              &nbsp;&nbsp;NaganoCake
             </p>
           </h1>
          </div>
         </div>
         <div class="col-md-3">
          </div>
         <div class="col-md-5">
           <%= link_to "About" ,about_path,class: "btn btn-outline-dark" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
           <%= link_to "商品一覧" ,public_items_path,class: "btn btn-outline-dark" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
           <%= link_to "新規登録", new_customer_registration_path,class: "btn btn-outline-dark" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
           <%= link_to "ログイン", new_customer_session_path,class: "btn btn-outline-dark" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         </div>
       </div>
     </div>
    <% end %>

    <%= flash[:error] %>　　<%= notice %>
    <%= yield %>
  </body>
</html>